### ISSUE TITLE
Runtime error while implementing the code

### ISSUE THREAD

**Issue by AJAY31797** [p-ranav/DiverseDepth#1]
Hi, 

I am trying to run the DiverseDepth using your repo. I followed the instructions given in Readme file. The test data which I am trying to run the algorithm on is a simple folder, which contains 2 PNG images. 
The command line argument given is as follows:

`python -m tools.test_diversedepth_png --dataroot D:\DiversedepthAJ --dataset test_images --cfg_file lib/configs/resnext50_32x4d_diversedepth_regression_vircam --load_ckpt D:\DiversedepthAJ\model.pth`

The code is giving me Runtime error. The output is as follows:
 
`INFO parse_arg_base.py:  56: ----------------- Options ---------------
                  base_lr: 1e-05
                batchsize: 2
                 cfg_file: lib/configs/resnext50_32x4d_diversedepth_regression_vircam   [default: lib/configs/resnext_32x4d_nyudv2_c1]
                 dataroot: D:\DiversedepthAJ                    [default: None]
                  dataset: test_images                          [default: nyudv2_rel]
             dataset_list: None
         diff_loss_weight: 1
                    epoch: 100
                load_ckpt: D:\DiversedepthAJ\model.pth          [default: None]
               local_rank: 0
                loss_mode: SSIL_VNL
                    optim: SGD
                    phase: test
               phase_anno: test
              results_dir: ./evaluation
                   resume: False
         sample_depth_flg: False
       sample_ratio_steps: 10000
       sample_start_ratio: 0.1
         scale_decoder_lr: 1
              start_epoch: 0
               start_step: 0
                   thread: 1
              use_tfboard: False
----------------- End -------------------
INFO net_tools.py:  40: loading checkpoint D:\DiversedepthAJ\model.pth
torch.Size([1, 3, 480, 854])
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aagr657\DiverseDepth\tools\test_diversedepth_png.py", line 85, in <module>
    pred_depth, _ = model.module.depth_model(img_torch)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\DiverseDepth\lib\models\diverse_depth_model.py", line 160, in forward
    lateral_out, encoder_stage_size = self.encoder_modules(x)
                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\DiverseDepth\lib\models\lateral_net.py", line 74, in forward
    bottemup_blocks_out = [self.bottomup.res1(x)]
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\container.py", line 215, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aagr657\AppData\Local\anaconda3\envs\Diversedepth\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor`

Could you suggest why this might be happening? I have not made any changes in the source code. I am just trying to test it on two images, which are contained in 'test_images' folder in the root directory. I am running the code on pytorch 2.1.1, cuda 11.8, python 3.11. 

Thanks, 
Ajay

**Comment by p-ranav** [comment]
Does `torch.cuda.is_available()` return `True` for you?

**Comment by p-ranav** [comment]
I don't have a GPU configured for torch but this is what the output looks like for me:

```console
python3 -m tools.test_diversedepth_png --dataroot /Users/pranav/Desktop/example_frames --dataset any --cfg_file lib/configs/resnext50_32x4d_diversedepth_regression_vircam --load_ckpt ./DiverseDepth.pth
INFO parse_arg_base.py:  56: ----------------- Options ---------------
                  base_lr: 1e-05                         
                batchsize: 2                             
                 cfg_file: lib/configs/resnext50_32x4d_diversedepth_regression_vircam	[default: lib/configs/resnext_32x4d_nyudv2_c1]
                 dataroot: /Users/pranav/Desktop/example_frames	[default: None]
                  dataset: any                           	[default: nyudv2_rel]
             dataset_list: None                          
         diff_loss_weight: 1                             
                    epoch: 100                           
                load_ckpt: ./DiverseDepth.pth            	[default: None]
               local_rank: 0                             
                loss_mode: SSIL_VNL                      
                    optim: SGD                           
                    phase: test                          
               phase_anno: test                          
              results_dir: ./evaluation                  
                   resume: False                         
         sample_depth_flg: False                         
       sample_ratio_steps: 10000                         
       sample_start_ratio: 0.1                           
         scale_decoder_lr: 1                             
              start_epoch: 0                             
               start_step: 0                             
                   thread: 1                             
              use_tfboard: False                         
----------------- End -------------------
/home/pranav/dev/DiverseDepth/lib/core/config.py:132: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = AttrDict(yaml.load(f))
torch.Size([1, 3, 480, 854])
/home/pranav/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/torch/nn/functional.py:3769: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
tensor([[[[ 0.0046,  0.0028,  0.0155,  ...,  0.0194, -0.0003, -0.0012],
          [ 0.0044,  0.0031,  0.0153,  ...,  0.0230,  0.0044,  0.0031],
          [-0.0052, -0.0067,  0.0147,  ...,  0.0449,  0.0267,  0.0265],
          ...,
          [-0.0039, -0.0065,  0.0083,  ...,  0.0197,  0.0151,  0.0167],
          [-0.0117, -0.0130,  0.0058,  ..., -0.0024, -0.0030, -0.0024],
          [-0.0078, -0.0088,  0.0102,  ..., -0.0063, -0.0057, -0.0051]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
/home/pranav/dev/DiverseDepth/tools/test_diversedepth_png.py:46: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
  cmapper = matplotlib.cm.get_cmap(cmap)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0146,  0.0139,  0.0420,  ...,  0.0322, -0.0056, -0.0081],
          [ 0.0155,  0.0152,  0.0431,  ...,  0.0416,  0.0013, -0.0007],
          [-0.0031, -0.0024,  0.0541,  ...,  0.0971,  0.0456,  0.0450],
          ...,
          [-0.0027, -0.0074,  0.0093,  ...,  0.0188,  0.0146,  0.0175],
          [-0.0161, -0.0191,  0.0018,  ..., -0.0006, -0.0023, -0.0014],
          [-0.0117, -0.0146,  0.0061,  ..., -0.0019, -0.0034, -0.0022]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0081,  0.0093,  0.0355,  ...,  0.0403,  0.0052,  0.0017],
          [ 0.0086,  0.0100,  0.0358,  ...,  0.0495,  0.0070,  0.0025],
          [-0.0070, -0.0072,  0.0394,  ...,  0.1006,  0.0460,  0.0395],
          ...,
          [-0.0043, -0.0108,  0.0120,  ...,  0.0472,  0.0326,  0.0407],
          [-0.0232, -0.0268,  0.0018,  ..., -0.0120, -0.0102, -0.0049],
          [-0.0186, -0.0217,  0.0077,  ..., -0.0149, -0.0116, -0.0066]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0210,  0.0199,  0.0523,  ...,  0.0403, -0.0066, -0.0097],
          [ 0.0216,  0.0210,  0.0532,  ...,  0.0519,  0.0016, -0.0010],
          [-0.0019, -0.0008,  0.0669,  ...,  0.1196,  0.0558,  0.0548],
          ...,
          [-0.0033, -0.0075,  0.0064,  ...,  0.0100,  0.0081,  0.0102],
          [-0.0135, -0.0152,  0.0056,  ..., -0.0080, -0.0067, -0.0053],
          [-0.0112, -0.0123,  0.0082,  ..., -0.0083, -0.0073, -0.0059]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 1.7300e-02,  1.3989e-02,  4.3546e-02,  ...,  4.5487e-03,
           -1.8038e-05, -4.6992e-04],
          [ 1.8062e-02,  1.3829e-02,  4.3373e-02,  ...,  5.9548e-03,
            1.9359e-03,  1.5355e-03],
          [ 1.2654e-03, -6.4300e-03,  5.0683e-02,  ...,  2.2440e-02,
            1.8103e-02,  1.6953e-02],
          ...,
          [ 1.8499e-03, -3.2823e-03,  1.7334e-02,  ...,  4.5358e-02,
            3.1318e-02,  3.7753e-02],
          [-1.7968e-02, -2.0510e-02,  6.5937e-03,  ..., -3.6566e-03,
           -4.6945e-03, -1.6130e-04],
          [-1.2972e-02, -1.4967e-02,  1.2454e-02,  ..., -5.6817e-03,
           -6.3161e-03, -2.3685e-03]]]], grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0057,  0.0049,  0.0162,  ...,  0.0321, -0.0014, -0.0046],
          [ 0.0052,  0.0043,  0.0158,  ...,  0.0399,  0.0046,  0.0022],
          [-0.0029, -0.0057,  0.0160,  ...,  0.0923,  0.0478,  0.0468],
          ...,
          [ 0.0007, -0.0079,  0.0158,  ...,  0.0429,  0.0291,  0.0351],
          [-0.0191, -0.0245,  0.0009,  ..., -0.0130, -0.0139, -0.0101],
          [-0.0124, -0.0173,  0.0089,  ..., -0.0168, -0.0172, -0.0139]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0099,  0.0083,  0.0366,  ...,  0.0384, -0.0062, -0.0090],
          [ 0.0102,  0.0096,  0.0373,  ...,  0.0494,  0.0020, -0.0003],
          [-0.0064, -0.0057,  0.0459,  ...,  0.1140,  0.0541,  0.0535],
          ...,
          [-0.0026, -0.0097,  0.0146,  ...,  0.0067,  0.0046,  0.0076],
          [-0.0245, -0.0283, -0.0010,  ..., -0.0087, -0.0079, -0.0059],
          [-0.0194, -0.0226,  0.0056,  ..., -0.0105, -0.0093, -0.0073]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0256,  0.0218,  0.0501,  ...,  0.0286, -0.0010, -0.0043],
          [ 0.0280,  0.0235,  0.0483,  ...,  0.0334,  0.0017, -0.0017],
          [ 0.0124,  0.0068,  0.0552,  ...,  0.0577,  0.0189,  0.0174],
          ...,
          [ 0.0096,  0.0049,  0.0191,  ...,  0.0234,  0.0192,  0.0216],
          [-0.0074, -0.0100,  0.0073,  ...,  0.0004, -0.0015, -0.0009],
          [-0.0057, -0.0083,  0.0071,  ..., -0.0013, -0.0029, -0.0019]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0185,  0.0151,  0.0262,  ...,  0.0146, -0.0016, -0.0036],
          [ 0.0182,  0.0146,  0.0260,  ...,  0.0207,  0.0028,  0.0009],
          [-0.0009, -0.0054,  0.0234,  ...,  0.0346,  0.0144,  0.0142],
          ...,
          [-0.0023, -0.0047,  0.0062,  ...,  0.0477,  0.0310,  0.0373],
          [-0.0094, -0.0112, -0.0002,  ..., -0.0029, -0.0062, -0.0018],
          [-0.0068, -0.0086,  0.0026,  ..., -0.0055, -0.0078, -0.0040]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 1.4371e-02,  1.4381e-02,  4.3377e-02,  ...,  9.6577e-03,
            2.3017e-03,  2.3425e-03],
          [ 1.5762e-02,  1.5703e-02,  4.2710e-02,  ...,  1.2179e-02,
            4.7990e-03,  4.8593e-03],
          [ 8.1059e-04,  7.3257e-04,  5.0304e-02,  ...,  2.1879e-02,
            1.6047e-02,  1.6593e-02],
          ...,
          [-2.1387e-05, -6.7942e-03,  1.5674e-02,  ...,  4.2183e-02,
            2.8504e-02,  3.4729e-02],
          [-1.9707e-02, -2.3818e-02,  1.7009e-03,  ..., -8.1380e-03,
           -8.1599e-03, -4.1336e-03],
          [-1.4434e-02, -1.8319e-02,  7.9717e-03,  ..., -1.0788e-02,
           -1.0043e-02, -6.4053e-03]]]], grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0068,  0.0051,  0.0235,  ...,  0.0268, -0.0042, -0.0062],
          [ 0.0071,  0.0061,  0.0246,  ...,  0.0349,  0.0011, -0.0005],
          [-0.0049, -0.0053,  0.0292,  ...,  0.0830,  0.0389,  0.0376],
          ...,
          [-0.0036, -0.0092,  0.0117,  ...,  0.0348,  0.0221,  0.0280],
          [-0.0226, -0.0256, -0.0002,  ..., -0.0108, -0.0101, -0.0066],
          [-0.0173, -0.0200,  0.0056,  ..., -0.0133, -0.0116, -0.0085]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0226,  0.0195,  0.0480,  ...,  0.0137, -0.0018, -0.0008],
          [ 0.0241,  0.0204,  0.0459,  ...,  0.0178,  0.0010,  0.0019],
          [ 0.0119,  0.0075,  0.0579,  ...,  0.0483,  0.0281,  0.0298],
          ...,
          [ 0.0046, -0.0003,  0.0143,  ...,  0.0543,  0.0351,  0.0426],
          [-0.0083, -0.0113,  0.0071,  ..., -0.0061, -0.0094, -0.0040],
          [-0.0060, -0.0091,  0.0079,  ..., -0.0096, -0.0119, -0.0071]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0105,  0.0090,  0.0290,  ...,  0.0215, -0.0071, -0.0122],
          [ 0.0099,  0.0085,  0.0272,  ...,  0.0275, -0.0027, -0.0084],
          [-0.0078, -0.0091,  0.0229,  ...,  0.0489,  0.0141,  0.0094],
          ...,
          [-0.0012, -0.0019,  0.0051,  ...,  0.0361,  0.0237,  0.0290],
          [-0.0064, -0.0066,  0.0018,  ..., -0.0057, -0.0071, -0.0036],
          [-0.0053, -0.0056,  0.0025,  ..., -0.0070, -0.0080, -0.0047]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)
torch.Size([1, 3, 480, 854])
tensor([[[[ 0.0115,  0.0101,  0.0392,  ...,  0.0330, -0.0097, -0.0119],
          [ 0.0119,  0.0113,  0.0401,  ...,  0.0434, -0.0027, -0.0046],
          [-0.0059, -0.0055,  0.0478,  ...,  0.1075,  0.0486,  0.0483],
          ...,
          [-0.0008, -0.0073,  0.0142,  ...,  0.0450,  0.0297,  0.0364],
          [-0.0191, -0.0229,  0.0016,  ..., -0.0064, -0.0079, -0.0035],
          [-0.0141, -0.0176,  0.0078,  ..., -0.0095, -0.0101, -0.0061]]]],
       grad_fn=<ConvolutionBackward0>)
(1, 1, 480, 854)

```

**Comment by AJAY31797** [comment]
Yes, torch.cuda.is_available() returns true to me. 
I tried to run the code on Google Colab as well. Still getting the same error.
Any other possible causes of this error? Are there any specific requirements for the input images? It seems from the error description that the error is being originated because of some size difference in a convolutional layer. 

Thanks, 
Ajay
